import comp from "F:/code_lib/BlogWeb/weiruyi.github.io-main/src/.vuepress/.temp/pages/posts/项目/heimaLeadnews/1_热文章计算.html.vue"
const data = JSON.parse("{\"path\":\"/posts/%E9%A1%B9%E7%9B%AE/heimaLeadnews/1_%E7%83%AD%E6%96%87%E7%AB%A0%E8%AE%A1%E7%AE%97.html\",\"title\":\"热文章计算\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"热文章计算\",\"date\":\"2024-10-15T16:24:22.000Z\",\"tags\":\"项目\",\"category\":\"黑马头条\",\"icon\":\"/img/Kafka.svg\",\"description\":\"热文章计算 一、热点文章-定时计算 1、 需求分析 需求：为每个频道缓存热度较高的30条文章优先展示\",\"gitInclude\":[],\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mister-hope.github.io/posts/%E9%A1%B9%E7%9B%AE/heimaLeadnews/1_%E7%83%AD%E6%96%87%E7%AB%A0%E8%AE%A1%E7%AE%97.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"chuoer\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"热文章计算\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"热文章计算 一、热点文章-定时计算 1、 需求分析 需求：为每个频道缓存热度较高的30条文章优先展示\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://mister-hope.github.io/image\\\\project\\\\p18.png\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"chuoer47\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-10-15T16:24:22.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"热文章计算\\\",\\\"image\\\":[\\\"https://mister-hope.github.io/image\\\\\\\\project\\\\\\\\p18.png\\\",\\\"https://mister-hope.github.io/image\\\\\\\\project\\\\\\\\p19.png\\\",\\\"https://mister-hope.github.io/image\\\\\\\\project\\\\\\\\p20.png\\\",\\\"https://mister-hope.github.io/image\\\\\\\\project\\\\\\\\p21.png\\\"],\\\"datePublished\\\":\\\"2024-10-15T16:24:22.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"chuoer47\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"一、热点文章-定时计算\",\"slug\":\"一、热点文章-定时计算\",\"link\":\"#一、热点文章-定时计算\",\"children\":[{\"level\":3,\"title\":\"1、 需求分析\",\"slug\":\"_1、-需求分析\",\"link\":\"#_1、-需求分析\",\"children\":[]},{\"level\":3,\"title\":\"2、 实现思路\",\"slug\":\"_2、-实现思路\",\"link\":\"#_2、-实现思路\",\"children\":[]},{\"level\":3,\"title\":\"3、 实现步骤\",\"slug\":\"_3、-实现步骤\",\"link\":\"#_3、-实现步骤\",\"children\":[]},{\"level\":3,\"title\":\"4、查询文章接口改造\",\"slug\":\"_4、查询文章接口改造\",\"link\":\"#_4、查询文章接口改造\",\"children\":[]}]},{\"level\":2,\"title\":\"二、热点文章实时计算\",\"slug\":\"二、热点文章实时计算\",\"link\":\"#二、热点文章实时计算\",\"children\":[{\"level\":3,\"title\":\"1、 思路说明\",\"slug\":\"_1、-思路说明\",\"link\":\"#_1、-思路说明\",\"children\":[]},{\"level\":3,\"title\":\"2、 功能实现\",\"slug\":\"_2、-功能实现\",\"link\":\"#_2、-功能实现\",\"children\":[]}]}],\"readingTime\":{\"minutes\":10.48,\"words\":3145},\"filePathRelative\":\"posts/项目/heimaLeadnews/1_热文章计算.md\",\"localizedDate\":\"2024年10月16日\",\"excerpt\":\"<!--more--->\\n<h1>热文章计算</h1>\\n<h2>一、热点文章-定时计算</h2>\\n<h3>1、 需求分析</h3>\\n<p>需求：为每个频道缓存热度较高的30条文章优先展示</p>\\n\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
